# Site settings
baseurl = "https://openarmsministry.org/"
# baseurl = "http://b48cd5d2.ngrok.io/"
languageCode = "en-us"
title = "Open Arms Ministry"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-82352339-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Open Arms Ministry Chicago"
  description = ""

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "feedback@openarmsministry.org"
  
  # stripeKey = "pk_test_4EyldUsSlF1XNcXNadhdHCWf"
  stripeKey = "pk_live_37kWx8MUQw8vfC9hO1sVU2qr"
  [params.volunteer]
    enable = true
    title = "Volunteer"
    description = "Committed regular volunteers are needed in order for the Drop-In and Food Pantry to function effectively.  <br><br> We would love for you to volunteer with us! <br> Please fill [this form](http://bit.ly/OAMvolunteer) out: and we will be in touch."
  
  [params.program]
    enable = true
    title = "Program Hours/Info"
    description = "<h4> Drop-In </h4> Tuesday to Thursday <br> 10am-2pm <br> <a href='tel:7732523210'>773-252-3210</a> <br> <a href='mailto:dropin@openarmsministry.org'>dropin@openarmsministry.org</a> <br>  <br> <h4>Food Pantry</h4> Wednesday <br> 4pm-6pm <br> <a href='mailto:pantry@openarmsministry.org'>pantry@openarmsministry.org</a>"
  # Hero Section
  [params.hero]
    logo = "logo.png"
    title = "Open Arms Ministry"
    description = "Share. Connect. Provide."
    buttonText = "Learn more"

  # about section
  [params.about]
    enable = true
    title = "Who We Are"
    description = "Open Arms Ministry supports and partners with those struggling with homelessness, poverty, and food insecurity to enhance human dignity, community, and opportunity. <br><br> Open Arms Ministry is a 501&#40;c&#41;3 organization."
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "wall-panhandling.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Services We Provide"
    description = "Open Arms Ministry has two programs addressing homelessness, poverty, and food insecurity on the northwest side of Chicago."
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "pic02.jpg"

    [[params.skills]]
      icon = "fa-child"
      title = "Drop-In"
      description = "Open Arms Drop-In provides basic relief services to individuals struggling with homelessness or at risk of becoming homeless. More than relief from the weather outside, this drop-in program enables those who come to share a meal with friends and get connected to resources. <br><br> Guests also receive help meeting physical needs like clothing, toiletries, and basic healthcare. Referrals are available for services such as overnight shelter, recovery, and education."
    
    [[params.skills]]
      icon = "fa-cutlery"
      title = "Food Pantry"
      description = "Working in conjunction with the Greater Chicago Food Depository, the Open Arms Food Pantry serves families and individuals who live in the area bounded by **Irving Park, Fullerton, Pulaski, and Western**. <br></br>All are welcome (proof of address required), including those who have experienced job loss, illness in the family, unexpected expenses, and more."

  # infos section
  [params.infos]
    enable = true
    title = "One more thing"
    description = "We are currently in the development stage, aiming to provide the best services while being good neighbors in the community.  If you are interested in volunteering, donating, or providing any feedback, please don't hesistate to contact us below!"
    # the picture is storead at static/images/
    # picture = "pic03.jpg"

  [params.donate]
    enable = true
    title = "Donate"
    description = "We would love for you to contribute to our mission of enhancing human diginity and providing food and essential services for people in Chicago. <br> <br> Open Arms Ministry is a 501&#40;c&#41;3 non-profit organization; donations are tax-deductible."
    buttonLink= "https://donate.openarmsministry.org"
    buttonText= "Donate Platform"
  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form
  [params.subscribe]
    enable = true
    title = "Subscribe to our Newsletter"
    description = "We are excited to share with you what we are working on.  If you are interested, please follow the link below and subscribe to our newsletter."
    buttonText = "Subscribe"
    link = "http://eepurl.com/cjtmJv"
    
  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/openarmschicago"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Â© Open Arms Ministry"
