# Site settings
baseurl = "https://openarmsministry.org/"
# baseurl = "http://b48cd5d2.ngrok.io/"
languageCode = "en-us"
title = "Highlights"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-82352339-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Open Arms Ministry Chicago"
  description = ""

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "feedback@openarmsministry.org"
  
  # stripeKey = "pk_test_4EyldUsSlF1XNcXNadhdHCWf"
  stripeKey = "pk_live_37kWx8MUQw8vfC9hO1sVU2qr"
  [params.volunteer]
    enable = true
    title = "Volunteer"
    description = "We would love for you to volunteer with us! <br> Please fill [this form](http://bit.ly/OAMvolunteer) out: and we will be in touch."
  
  [params.program]
    enable = true
    title = "Program Hours"
    description = "<h4> Drop-in Program </h4> Tuesday to Thursday <br> 10am-2pm <br> <br> <h4>Food Pantry</h4> Wednesday <br> 4pm-6pm"
  # Hero Section
  [params.hero]
    logo = "logo.png"
    title = "Open Arms Ministry"
    description = "We are a non-profit 501c3 organization located in Logan Square Chicago, aiming to provide essential services to the individuals and families."
    buttonText = "Learn more"

  # about section
  [params.about]
    enable = true
    title = "Who We Are"
    description = "Open Arms Ministry supports and partners with those struggling with homelessness, poverty, and food insecurity to enhance human dignity, community, and opportunity."
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "wall-panhandling.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Service We Provide"
    description = "We provide various services through our Food Pantry and Drop-in Center"
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "pic02.jpg"

    [[params.skills]]
      icon = "fa-cutlery"
      title = "Food for Families"

    [[params.skills]]
      icon = "fa-child"
      title = "Fresh Clothing"

    [[params.skills]]
      icon = "fa-comments-o"
      title = "Community"

    [[params.skills]]
      icon = "fa-coffee"
      title = "Light Refreshments and Lunch"
  # infos section
  [params.infos]
    enable = true
    title = "One more thing"
    description = "We are currently in the development stage, aiming to provide the best services while being good neighbors in the community.  If you are interested in volunteering, donating, or providing any feedback, please don't hesistate to contact us below!"
    # the picture is storead at static/images/
    # picture = "pic03.jpg"

  [params.donate]
    enable = true
    title = "Donate"
    description = "We would love for you to contribute to our mission of enhancing human diginity and providing food and essential services for people in Chicago. (Feature goes live on 8/28/2016)"
  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = false

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagram"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Â© Open Arms Ministry"
